version: '3.7'

services:
  django_gunicorn:
    image: djangodocker:latest
    volumes:
      - static:/staticfiles
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "800:800"
    depends_on:
      - django_gunicorn

volumes:
  static: